---
version:
- Server v3.x
- Server Admin
---
= CircleCI Server v3.x Load Balancers
:page-layout: classic-docs
:page-liquid:
:page-description: Use this guide to make the frontend load balancer private.
:icons: font
:toc: macro
:toc-title:

CircleCI server uses load balancers to manage network traffic entering and leaving the Kubernetes services cluster. The three load balancers managing traffic to the Nomad cluster are internal to the VPC and they manage the distribution of jobs to the various compute resources. 

The frontend load balancer manages traffic coming from developers and your VCS, including through the API, the CLI, and CircleCI app. The frontend load balancer is public by default, but can be made private.

toc::[]

== Make the frontend load balancer private

[WARNING]
==== 
**Webhooks:** If you choose to make the frontend load balancer private, the following conditions must be met, dependent on VCS, for webhooks to work: 

* **GitHub Enterprise** – your CircleCI server installation must be in the same internal network as GHE. 
* **GitHub.com** – set up a proxy for incoming webhooks and set it as override for the webhook host URL. This setting can be found under **Admin Settings** > **System Settings** > **Override webhook host URL** from the CircleCI app.
====

NOTE: The Private load balancers option only works with installations on CircleCI server on GKE or EKS.

. From the management console, select **Config** from the menu bar and locate the **Private load balancers** option under **General Settings**.

. Check the box next to **Private load balancers**.
+
NOTE: If you are using Let's Encrypt TLS certificates, this box will not be visible as Let's Encrypt doesn't work with private installations. Uncheck the box for Let's Encrypt to make the Private load balancer option appear.

If you are changing this setting after the initial deployment of CircleCI server, you may need to delete the old public load balancer so that Kubernetes will request a new load balancer with the new configuration.


== Using ACM TLS Certificates

If you have deployed your CircleCI Server instance on AWS, you may consider using [ACM](https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html) to manage your TLS certificates. You can follow the [ACM documentation](https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-public.html) for instructions on how to generate ACM certificates.

Once your have generated your certificates, you can enabled ACM in your KOTS admin console under the Frontend section. You only need to check the ACM box, provide your ACM ARN and save your config.

[WARNING]
==== 
Enabling ACM is a destructive change to your frontend service. The service will have to be regenerated to allow the use of your ACM certificates and so the associated loadbalancer will also be regenerated. 
You will need to reroute your DNS records to the new loadbalancer once deployed.
====